name: postgre_sourcedb

version: '3'
services:
  data_download:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: data_download
    volumes:
      - /Users/sophialawal/Documents/capstone/OlistELT/Ingestion/data:/root/ingestion/data


  postgre:
    image: postgres:16.3-bullseye
    container_name: postgre
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-notsecure}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce}
    ports:
      - "5434:5432"
    depends_on:
      data_download:
        condition: service_completed_successfully
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_script/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data: